# Generated by Django 6.0.2 on 2026-03-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
